import os
from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError

class SlackTool:
    def __init__(self):
        self.bot_token = os.getenv("SLACK_BOT_TOKEN")
        self.channel_id = os.getenv("SLACK_CHANNEL_ID")
        self.enabled = bool(self.bot_token and self.channel_id)
        
        if self.enabled:
            self.client = WebClient(token=self.bot_token)
            print(f"✅ Slack notifications enabled (Channel: {self.channel_id})")
        else:
            print("⚠️  Slack not configured - skipping Slack notifications")
    
    def send_report(self, report_title: str, report_content: str):
        """Send a formatted report to Slack"""
        if not self.enabled:
            print("⚠️  Slack notification skipped (not configured)")
            return False
        
        try:
            # Create rich message blocks
            blocks = [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": f"📊 {report_title}",
                        "emoji": True
                    }
                },
                {
                    "type": "divider"
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": report_content
                    }
                },
                {
                    "type": "context",
                    "elements": [
                        {
                            "type": "mrkdwn",
                            "text": f"🤖 Generated by Doctor Report Bot • <!date^{int(os.times()[4])}^{{date_short}} at {{time}}|now>"
                        }
                    ]
                }
            ]
            
            # Send message
            response = self.client.chat_postMessage(
                channel=self.channel_id,
                text=report_title,  # Fallback text
                blocks=blocks
            )
            
            print(f"✅ Report sent to Slack (ts: {response['ts']})")
            return True
            
        except SlackApiError as e:
            print(f"❌ Slack error: {e.response['error']}")
            return False
        except Exception as e:
            print(f"❌ Error sending to Slack: {e}")
            return False
    
    def test_connection(self):
        """Test if Slack connection works"""
        if not self.enabled:
            return False, "Slack not configured"
        
        try:
            # Test API call
            response = self.client.auth_test()
            bot_name = response['user']
            return True, f"Connected as {bot_name}"
        except SlackApiError as e:
            return False, f"Auth failed: {e.response['error']}"
        except Exception as e:
            return False, str(e)